name: CI Pull Requests
on:
  [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - name: Install dangerJS
        run: npm test
      - name: Test dangerJS
        run: |
          yarn init -y
          yarn add danger --dev
          yarn install
      - name: Danger
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



