name: CI Pull Requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install yarn
        run: |
          yarn install
      - name: Test Danger
        run: |
          yarn test
          ls -a
      - name: Danger ci
        if: ${{ always() }}
        run: |
          npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
